name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actalog/check-ci@main
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - run: docker image build -t servicespack/tasks-api:latest -t servicespack/tasks-api:$(npm pkg get version | sed 's/"//g') .
      - run: docker login -u servicespack -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker image push -a servicespack/tasks-api
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: servicespack
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: servicespack/tasks-api
